// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwU6s1mtn7ZthOaXyHCWlBIap6O1D69K0',
    appId: '1:369816118086:web:5a19b94b386469e2c7bb47',
    messagingSenderId: '369816118086',
    projectId: 'unnamed-flutter-project',
    authDomain: 'unnamed-flutter-project.firebaseapp.com',
    storageBucket: 'unnamed-flutter-project.appspot.com',
    measurementId: 'G-LN2TDWVD6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcKg-1GW15qt94DITBLbw_tQxXQe2WM4',
    appId: '1:369816118086:android:04e5a9693a0bea72c7bb47',
    messagingSenderId: '369816118086',
    projectId: 'unnamed-flutter-project',
    storageBucket: 'unnamed-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvr1vZY_3yQgphbdBvVrKiN5yt-bx5qr8',
    appId: '1:369816118086:ios:c47d82ce0ee7e732c7bb47',
    messagingSenderId: '369816118086',
    projectId: 'unnamed-flutter-project',
    storageBucket: 'unnamed-flutter-project.appspot.com',
    iosClientId: '369816118086-75t95cfoo11uvtoce7hp9j1mqvagbkd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.borrowPlz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvr1vZY_3yQgphbdBvVrKiN5yt-bx5qr8',
    appId: '1:369816118086:ios:c47d82ce0ee7e732c7bb47',
    messagingSenderId: '369816118086',
    projectId: 'unnamed-flutter-project',
    storageBucket: 'unnamed-flutter-project.appspot.com',
    iosClientId: '369816118086-75t95cfoo11uvtoce7hp9j1mqvagbkd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.borrowPlz',
  );
}
